export const ComponentsConfiguration = {
    components: [
        {
            compId: 'registration',
            parentId: '',
            displayNameTag: 'registration',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'login',
            parentId: '',
            displayNameTag: 'login',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'ChartTable',
            parentId: '',
            displayNameTag: 'Chart Table',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'AdminLogin',
            parentId: '',
            displayNameTag: 'Admin Login',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'Categories',
            parentId: '',
            displayNameTag: 'Categories',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'ShowCategory',
            parentId: '',
            displayNameTag: 'Show Categories',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'EditCategory',
            parentId: '',
            displayNameTag: 'Edit Category',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'Steps',
            parentId: '',
            displayNameTag: 'Steps',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'ShowSteps',
            parentId: '',
            displayNameTag: 'Show Steps',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'EditStep',
            parentId: '',
            displayNameTag: 'Edit Step',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'UserRole',
            parentId: '',
            displayNameTag: 'User Role',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'UserDesignation',
            parentId: '',
            displayNameTag: 'User Designation',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'DepartmentListing',
            parentId: '',
            displayNameTag: 'Department Listing',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'EditDepartment',
            parentId: '',
            displayNameTag: 'Edit Department',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'UserDepartment',
            parentId: '',
            displayNameTag: 'User Department',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'AddUser',
            parentId: '',
            displayNameTag: 'Add Admin User',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'UserListing',
            parentId: '',
            displayNameTag: 'User Listing',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'EditUserRole',
            parentId: '',
            displayNameTag: 'Edit User Role',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'ApplicationCategory',
            parentId: '',
            displayNameTag: 'Application Category',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'ApplicationForms',
            parentId: '',
            displayNameTag: 'Application Forms',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'SubmitApplications',
            parentId: '',
            displayNameTag: 'Submited Applications',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'SingleSubmitedApplication',
            parentId: '',
            displayNameTag: 'Single Submited Application',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'AdminPortalDashboard',
            parentId: '',
            displayNameTag: 'Admin Portal Dashboard',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'AdminLogout',
            parentId: '',
            displayNameTag: 'Admin Logout Button',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'UserLogout',
            parentId: '',
            displayNameTag: 'User Logout Button',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'CSSPortalDashboard',
            parentId: '',
            displayNameTag: 'CSS Portal Dashboard',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'EditItem',
            parentId: '',
            displayNameTag: 'Edit single Item',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'RoleListing',
            parentId: '',
            displayNameTag: 'User Role Listing',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'RolePermission',
            parentId: '',
            displayNameTag: 'Add Role Permission',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'AdminNavbar',
            parentId: '',
            displayNameTag: 'Admin Navbar',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'ApprovalWorkflowStep',
            parentId: '',
            displayNameTag: 'Approval Workflow Step',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'DesignationListing',
            parentId: '',
            displayNameTag: 'Designation Listing',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'EditDesignation',
            parentId: '',
            displayNameTag: 'Edit Designation',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'ApplicationWorkflow',
            parentId: '',
            displayNameTag: 'Application Workflow',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'RegisterUserList',
            parentId: '',
            displayNameTag: 'Register Users List',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'RegisterUserDetails',
            parentId: '',
            displayNameTag: 'Register Users Details',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'MyInbox',
            parentId: '',
            displayNameTag: 'My Inbox',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'ChartTable',
            parentId: '',
            displayNameTag: 'Application Progress Status Report',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'ApplicationsReport',
            parentId: '',
            displayNameTag: 'Applications Report',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'ApplicationStatus',
            parentId: '',
            displayNameTag: 'Application Progress Status',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'CategoryWiseApplications',
            parentId: '',
            displayNameTag: 'Category Wise Applications Report',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'CSSTrackAndMonitor',
            parentId: '',
            displayNameTag: 'CSS Track And Monitor Report',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {

            compId: 'VouchersListing',
            parentId: '',
            displayNameTag: 'Vouchers Listing',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'VoucherDetails',
            parentId: '',
            displayNameTag: 'Voucher Details',
             displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'DeathNOCReport',
            parentId: '',
            displayNameTag: 'Death NOC Report',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'EditSubmitedApplication',
            parentId: '',
            displayNameTag: 'Edit Submited Application',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
        {
            compId: 'ForgotPassword',
            parentId: '',
            displayNameTag: 'Forgot Password',
            displayImage: 'imageIcon',
            styles: ['buttonComponentStyles'],
            settings: [],
            compFields: [],
        },
    ],
};
