export const ComponentsConfiguration = {
    components: [
        {
            compId: 'accumulatedLossTable',
            parentId: 'table',
            displayNameTag: 'Accumulated Loss ',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'listOfParticipants',
            parentId: 'table',
            displayNameTag: 'List of Participants',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Market',
                    settingType: 'dropDown',
                    dataKey: 'market',
                    settingData: [
                        {
                            uniqueKey: 'm',
                            displayValue: 'Main Market',
                            value: 1,
                        },
                        {
                            uniqueKey: 'p',
                            displayValue: 'Premier Market',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'mutualFundTable',
            parentId: 'table',
            displayNameTag: 'Mutual Fund',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'researchReportTable',
            parentId: 'table',
            displayNameTag: 'Research Report Table',
            displayImage: 'tableIcon',
        },
        {
            compId: 'news',
            parentId: '',
            displayNameTag: 'News',
            displayImage: 'galleryIcon',
            compFields: [],
        },
        {
            compId: 'newsView',
            parentId: '',
            displayNameTag: 'News View',
            displayImage: 'galleryIcon',
            compFields: [],
        },
        {
            compId: 'rulebook',
            parentId: '',
            displayNameTag: 'BK Rule Book',
            displayImage: 'slidesIcon',
            compFields: [],
        },
        {
            compId: 'analystConferences',
            parentId: '',
            displayNameTag: 'Analyst Conferences',
            displayImage: 'slidesIcon',
            compFields: [],
        },
        {
            compId: 'cmadecision',
            parentId: '',
            displayNameTag: 'CMA Decision',
            compFields: [],
        },
        {
            compId: 'balanceSheet',
            parentId: '',
            displayNameTag: 'Balance Sheet',
            displayImage: 'slidesIcon',
            settings: [
                {
                    displayTitle: 'Enter PDF URL',
                    settingType: 'textInput',
                    dataKey: 'inputVal',
                },
            ],
            compFields: [],
        },
        {
            compId: 'datavendors',
            parentId: '',
            displayNameTag: 'Data Vendors',
            displayImage: 'slidesIcon',
            compFields: [],
        },
        {
            compId: 'bkReports',
            parentId: '',
            displayNameTag: 'BK Reports',
            displayImage: 'slidesIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Custom Collections',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: 'ms',
                            displayValue: 'Market Summary',
                            value: 1,
                        },
                        {
                            uniqueKey: 'sc',
                            displayValue: 'Summary Chart',
                            value: 2,
                        },
                        {
                            uniqueKey: 'sbs',
                            displayValue: 'Summary By Sector',
                            value: 3,
                        },
                        {
                            uniqueKey: 'mr',
                            displayValue: 'Monthly Report Details Chart',
                            value: 4,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'financialinfoform',
            parentId: '',
            displayNameTag: 'Financial Information Forms',
            displayImage: 'slidesIcon',
        },
        {
            compId: 'corporateProfile',
            parentId: '',
            displayNameTag: 'Corporate Profile',
            displayImage: 'slidesIcon',
            settings: [
                {
                    displayTitle: 'URL for PDF',
                    settingType: 'textInput',
                    dataKey: 'inputVal',
                },
            ],
            compFields: [],
        },
        {
            compId: 'marketparticipants',
            parentId: '',
            displayNameTag: 'Market Participants Forms',
            displayImage: 'slidesIcon',
            compFields: [],
        },
        {
            compId: 'fundMonthlyInfo',
            parentId: '',
            displayNameTag: 'Fund Monthly Info',
            displayImage: 'slidesIcon',
            settings: [
                {
                    displayTitle: 'Enter PDF URL',
                    settingType: 'textInput',
                    dataKey: 'inputVal',
                },
            ],
            compFields: [],
        },
        {
            compId: 'violationcommittee',
            parentId: '',
            displayNameTag: 'Violation Committee',
            displayImage: 'slidesIcon',
            compFields: [],
        },
        {
            compId: 'marketReport',
            parentId: '',
            displayNameTag: 'Market Report',
            displayImage: 'slidesIcon',
            compFields: [],
        },
        {
            compId: 'circuitBreaker',
            parentId: '',
            displayNameTag: 'Circuit Breaker',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'delisted',
            parentId: '',
            displayNameTag: 'Delisted Companies',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'reit',
            parentId: '',
            displayNameTag: 'REITS',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'corporateActions',
            parentId: '',
            displayNameTag: 'Corporate Actions',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'offMarketTrade',
            parentId: '',
            displayNameTag: 'Off Market Trades',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'cmaAnnouncements',
            parentId: '',
            displayNameTag: 'CMA Announcements',
            displayImage: 'slidesIcon',
            compFields: [],
        },
        {
            compId: 'listedcompanies',
            parentId: '',
            displayNameTag: 'Listed Companies',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'normalMarketSize',
            parentId: '',
            displayNameTag: 'Normal Market Size Table',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'footerFileList',
            parentId: '',
            displayNameTag: 'Footer File Lists',
            displayImage: 'slidesIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Custom Collections',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: 'pls',
                            displayValue: 'Pledge Of Listed Securities',
                            value: 1,
                        },
                        {
                            uniqueKey: 'ait',
                            displayValue: 'Active And Inactive Trading Accounts',
                            value: 2,
                        },
                        {
                            uniqueKey: 'tnc',
                            displayValue: 'Trading Volumes According To Nationality And Category',
                            value: 3,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'pressCorner',
            parentId: '',
            displayNameTag: 'Press Release',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'marketIndices',
            parentId: '',
            displayNameTag: 'Market Indices',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'topStock',
            parentId: '',
            displayNameTag: 'Top Stock',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'mode',
                    settingData: [
                        {
                            uniqueKey: 'tg',
                            displayValue: 'Top Gainers by Percentages change',
                            value: 1,
                        },
                        {
                            uniqueKey: 'tl',
                            displayValue: 'Top Losers by Percentage Change',
                            value: 3,
                        },
                        {
                            uniqueKey: 'mavol',
                            displayValue: 'Most Active by Volume',
                            value: 4,
                        },
                        {
                            uniqueKey: 'mat',
                            displayValue: 'Most Active by Trades',
                            value: 5,
                        },
                        {
                            uniqueKey: 'maval',
                            displayValue: 'Most Active by Value',
                            value: 6,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'marketSummary',
            parentId: '',
            displayNameTag: 'Market Summary',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'ratios',
            parentId: '',
            displayNameTag: 'Ratios',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'financials',
            parentId: '',
            displayNameTag: 'Financials',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'sectorSummary',
            parentId: '',
            displayNameTag: 'Sector Summary',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'tradedCompanies',
            parentId: '',
            displayNameTag: 'Traded Companies',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'financialReportList',
            parentId: '',
            displayNameTag: 'Financial Report List',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Custom Collections',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Annual Report',
                            value: 1,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'Quarterly Report',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'executiveDecisions',
            parentId: '',
            displayNameTag: 'Executive Decisions',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Select Decision Type',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'CEO Decisions',
                            value: 1,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'Board of Directors Resolutions',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'financialData',
            parentId: '',
            displayNameTag: 'Financial Data Table',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'bankHoldingComponent',
            parentId: '',
            displayNameTag: 'Bank Holding Component',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'executiveTeam',
            parentId: '',
            displayNameTag: 'Executive Team Table',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'financialComparison',
            parentId: '',
            displayNameTag: 'Financial Comparison',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'researchReportsPage',
            parentId: '',
            displayNameTag: 'Research Reports Page',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'companies',
            parentId: '',
            displayNameTag: 'Companies',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'mmObligation',
            parentId: '',
            displayNameTag: 'Market Maker Obligation',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'marketNews',
            parentId: '',
            displayNameTag: 'Market News',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'reitsfunddisclosure',
            parentId: '',
            displayNameTag: 'REITs fund disclosure',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'mutualfunddisclosure',
            parentId: '',
            displayNameTag: 'Mutual Fund disclosure',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'economicIndicator',
            parentId: '',
            displayNameTag: 'Economic Indicator',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: 'EBROUSDBR.SP',
                            displayValue: 'Kuwait Oil Price',
                            value: 'KOP',
                        },
                        {
                            uniqueKey: 'EWTIUSDBR.SP',
                            displayValue: 'CPI',
                            value: 'CPI',
                        },
                        {
                            uniqueKey: 'SXAUUSDOZ.SP',
                            displayValue: 'GDP',
                            value: 'GDP',
                        },
                    ],
                },
            ],
        },
        {
            compId: 'indexPrice',
            parentId: '',
            displayNameTag: 'Index Price',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Premier Market',
                            value: '01',
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'Main Market',
                            value: '02',
                        },
                        {
                            uniqueKey: '3',
                            displayValue: 'All Share',
                            value: '03',
                        },
                        {
                            uniqueKey: '50',
                            displayValue: 'BK Main 50',
                            value: '50',
                        },
                        {
                            uniqueKey: '5',
                            displayValue: 'REITs',
                            value: 'T',
                        },
                    ],
                },

                {
                    displayTitle: 'Bound to Chart',
                    settingType: 'dropDown',
                    dataKey: 'bound',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Yes',
                            value: true,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'No',
                            value: false,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'proChart',
            parentId: '',
            displayNameTag: 'Pro Chart',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Enable OHLC',
                    settingType: 'dropDown',
                    dataKey: 'OHLC',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Yes',
                            value: true,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'No',
                            value: false,
                        },
                    ],
                },

                {
                    displayTitle: 'Enable period Selection',
                    settingType: 'dropDown',
                    dataKey: 'period',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Yes',
                            value: true,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'No',
                            value: false,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'sectorIndices',
            parentId: '',
            displayNameTag: 'Sector Indices',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'watchlist',
            parentId: '',
            displayNameTag: 'Watch list',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'suspendedCompanies',
            parentId: '',
            displayNameTag: 'Suspended Companies',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'agmAndEgm',
            parentId: '',
            displayNameTag: 'AGMs and EGMs',
            displayImage: 'galleryIcon',
            compFields: [],
        },
        {
            compId: 'boardsElection',
            parentId: '',
            displayNameTag: 'Boards Election',
            displayImage: 'galleryIcon',
            compFields: [],
        },
        {
            compId: 'companiesDisclosure',
            parentId: '',
            displayNameTag: 'Companies Disclosure',
            displayImage: 'galleryIcon',
            compFields: [],
        },
        {
            compId: 'insiderDisclosure',
            parentId: '',
            displayNameTag: 'Insiders Disclosure',
            displayImage: 'galleryIcon',
            compFields: [],
        },
        {
            compId: 'marketAnnouncement',
            parentId: '',
            displayNameTag: 'Market Announcement',
            displayImage: 'galleryIcon',
            compFields: [],
        },
        {
            compId: 'prevDayDisclosure',
            parentId: '',
            displayNameTag: 'Previous Days Disclosure',
            displayImage: 'galleryIcon',
            compFields: [],
        },
        {
            compId: 'tradingSystemAnnouncement',
            parentId: '',
            displayNameTag: 'Trading System Announcements',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'historicalNews',
            parentId: '',
            displayNameTag: 'Historical News And Announcements',
            displayImage: 'galleryIcon',
            compFields: [],
        },
        {
            compId: 'endOfDayData',
            parentId: '',
            displayNameTag: 'End of Day Data',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'market',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Regular Market',
                            value: 1,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'OTC Market',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'securityData',
            parentId: '',
            displayNameTag: 'Security Data',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Regular Market',
                            value: 1,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'OTC Market',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'sectoralData',
            parentId: '',
            displayNameTag: 'Sectoral Data',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Regular Market',
                            value: 1,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'OTC Market',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'discontinuedSectoralData',
            parentId: '',
            displayNameTag: 'Discontinued Sectoral Data',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'MarketTrades',
            parentId: '',
            displayNameTag: 'Market Data',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Regular Market',
                            value: 1,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'OTC Market',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'offMarketDeals',
            parentId: '',
            displayNameTag: 'Off Market Data',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Regular Market',
                            value: 1,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'OTC Market',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'corporateAction',
            parentId: '',
            displayNameTag: 'Corporate Action - Data Service Portal',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'foreingOwnershipData',
            parentId: '',
            displayNameTag: 'Foreign Ownership Data',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'buySellStats',
            parentId: '',
            displayNameTag: 'Buy Sell Status',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'tradingDaySecData',
            parentId: '',
            displayNameTag: 'Trading Day Security Data',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Regular Market',
                            value: 1,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'OTC Market',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'TradingDayTradeData',
            parentId: '',
            displayNameTag: 'Trading Day Trade Data',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Regular Market',
                            value: 1,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'OTC Market',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'tradingDayOrdersData',
            parentId: '',
            displayNameTag: 'Trading Day Order Data',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Regular Market',
                            value: 1,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'OTC Market',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'tradesData',
            parentId: '',
            displayNameTag: 'Trades Data',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'icwFileDownloader',
            parentId: '',
            displayNameTag: 'ICW File Download',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'summaryCompanyAnnouncements',
            parentId: '',
            displayNameTag: 'Summary - Company Announcements',
            displayImage: 'galleryIcon',
            compFields: [],
        },
        {
            compId: 'summaryCorporateAction',
            parentId: '',
            displayNameTag: 'Summary - Corporate Actions',
            displayImage: 'galleryIcon',
            compFields: [],
        },
        {
            compId: 'summaryResearchReport',
            parentId: '',
            displayNameTag: 'Summary - Research Report',
            displayImage: 'galleryIcon',
            compFields: [],
        },
        {
            compId: 'eventCalendar',
            parentId: '',
            displayNameTag: 'Summary - Event Calendar',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'changeInDisclosures',
            parentId: '',
            displayNameTag: 'Daily Report Of Changes In Disclosures',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'watchListMenu',
            parentId: '',
            displayNameTag: 'Watchlist Menu',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'contactForm',
            parentId: '',
            displayNameTag: 'Contact Form',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Information Center',
                            value: 1,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'Investor Relations',
                            value: 2,
                        },
                        {
                            uniqueKey: '3',
                            displayValue: 'Whistleblowing',
                            value: 3,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'IndexSummary',
            parentId: '',
            displayNameTag: 'Index Summary',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'TopStockAdvanced',
            parentId: '',
            displayNameTag: 'Top Stock Advanced',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'TopStockHistory',
            parentId: '',
            displayNameTag: 'Top Stock History',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'mode',
                    settingData: [
                        {
                            uniqueKey: 'tg',
                            displayValue: 'Top Gainers by Percentages change',
                            value: 1,
                        },
                        {
                            uniqueKey: 'tl',
                            displayValue: 'Top Losers by Percentage Change',
                            value: 3,
                        },
                        {
                            uniqueKey: 'mavol',
                            displayValue: 'Most Active by Volume',
                            value: 4,
                        },
                        {
                            uniqueKey: 'mat',
                            displayValue: 'Most Active by Trades',
                            value: 5,
                        },
                        {
                            uniqueKey: 'maval',
                            displayValue: 'Most Active by Value',
                            value: 6,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'EconomicIndicatorsAdvanced',
            parentId: '',
            displayNameTag: 'Economic Indicators Advanced',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'EconomicIndicatorsMenu',
            parentId: '',
            displayNameTag: 'Economic Indicators Menu',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'NewsTicker',
            parentId: '',
            displayNameTag: 'News Ticker',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'archiveReports',
            parentId: '',
            displayNameTag: 'Archive Reports',
            displayImage: 'slidesIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Custom Collections',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: 'ms',
                            displayValue: 'Market Summary',
                            value: 1,
                        },
                        {
                            uniqueKey: 'sbs',
                            displayValue: 'Summary By Sector',
                            value: 2,
                        },
                        {
                            uniqueKey: 'msc',
                            displayValue: 'Market Summary By Company',
                            value: 3,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'otcForms',
            parentId: '',
            displayNameTag: 'OTC Forms',
            displayImage: 'slidesIcon',
            compFields: [],
        },
        {
            compId: 'IndexSummaryReports',
            parentId: '',
            displayNameTag: 'Index Summary Reports',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'CompanyBasicInfo',
            parentId: '',
            displayNameTag: 'Company Basic Info',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'type',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Stock Profile',
                            value: 0,
                        },
                        {
                            uniqueKey: '3',
                            displayValue: 'REITs profile',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'InstrumentProfile',
            parentId: '',
            displayNameTag: 'Instrument Profile',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Instrument type',
                    settingType: 'dropDown',
                    dataKey: 'type',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Company',
                            value: 0,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'Fund',
                            value: 1,
                        },
                        {
                            uniqueKey: '3',
                            displayValue: 'REITs',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'CompanyOwnersInfo',
            parentId: '',
            displayNameTag: 'Company Owners Info',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Instrument type',
                    settingType: 'dropDown',
                    dataKey: 'type',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Company',
                            value: 0,
                        },

                        {
                            uniqueKey: '3',
                            displayValue: 'REITs',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'CompanyManagementInfo',
            parentId: '',
            displayNameTag: 'Company Management Info',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Instrument type',
                    settingType: 'dropDown',
                    dataKey: 'type',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Company',
                            value: 0,
                        },

                        {
                            uniqueKey: '3',
                            displayValue: 'REITs',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'StockSnapshot',
            parentId: '',
            displayNameTag: 'Stock Snapshot',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'type',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Stock Profile',
                            value: 0,
                        },
                        {
                            uniqueKey: '3',
                            displayValue: 'REITs profile',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'CompanySummary',
            parentId: '',
            displayNameTag: 'Company Summary',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'CompanySubsidiariesInfo',
            parentId: '',
            displayNameTag: 'Company Subsidiaries Info',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'IncomeStatement',
            parentId: '',
            displayNameTag: 'Income Statement FD',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'CashFlowStatement',
            parentId: '',
            displayNameTag: 'CashFlow Statement FD',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'RatiosAndIndicators',
            parentId: '',
            displayNameTag: 'Ratios And Indicators FD',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'DailyRatios',
            parentId: '',
            displayNameTag: 'Daily Ratios FD',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'PriceVolumeData',
            parentId: '',
            displayNameTag: 'Price Volume Data FD',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'BalanceSheet',
            parentId: '',
            displayNameTag: 'Balance Sheet',
            displayImage: 'tableIcon',
            settings: [
                {
                    displayTitle: 'URL for PDF',
                    settingType: 'textInput',
                    dataKey: 'inputVal',
                },
            ],
            compFields: [],
        },
        {
            compId: 'MarketStatus',
            parentId: '',
            displayNameTag: 'Market Status',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'listedCompaniesNews',
            parentId: '',
            displayNameTag: 'Listed Companies News',
            displayImage: 'galleryIcon',
        },
        {
            compId: 'EconomicIndicatorChart',
            parentId: '',
            displayNameTag: 'Economic Indicator Chart',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'BoursaChart',
            parentId: '',
            displayNameTag: 'Boursa Chart',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'ChartComparsion',
            parentId: '',
            displayNameTag: 'Chart Comparsion',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'IntradayChart',
            parentId: '',
            displayNameTag: 'Intraday Chart',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'ProfileChart',
            parentId: '',
            displayNameTag: 'Profile Chart',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'type',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Stock Profile',
                            value: 0,
                        },
                        {
                            uniqueKey: '3',
                            displayValue: 'REITs profile',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'CompanyAuditors',
            parentId: '',
            displayNameTag: 'Company Auditors',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'CompanyDirectors',
            parentId: '',
            displayNameTag: 'Company Directors',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'ServiceProviders',
            parentId: '',
            displayNameTag: 'Service Providers',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'OTCCompanies',
            parentId: '',
            displayNameTag: 'OTC Companies',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'fullCalendar',
            parentId: '',
            displayNameTag: 'Corporate Events Calendar',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'weeklyCompanyStats',
            parentId: '',
            displayNameTag: 'Bulletin - Company Stats',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'weeklyIndices',
            parentId: '',
            displayNameTag: 'Bulletin - Indices',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'weeklyMarketOverview',
            parentId: '',
            displayNameTag: 'Bulletin - Market Overview',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'MarketReportIndexSummary',
            parentId: '',
            displayNameTag: 'Market Report Index Summary',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'holdingReportComponent',
            parentId: '',
            displayNameTag: 'Holding Report Component',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'ProchartMenu',
            parentId: '',
            displayNameTag: 'Prochart Menu',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'BalanceSheetDetailed',
            parentId: '',
            displayNameTag: 'Balance Sheet FD',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'MarketMakers',
            parentId: '',
            displayNameTag: 'Market Makers',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'SummaryBySector',
            parentId: '',
            displayNameTag: 'Summary By Sector',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'MktWatchIndexPrice',
            parentId: '',
            displayNameTag: 'Market Watch Index Price',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Premier Market',
                            value: '01',
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'Main Market',
                            value: '02',
                        },
                        {
                            uniqueKey: '3',
                            displayValue: 'All Share',
                            value: '03',
                        },
                        {
                            uniqueKey: '50',
                            displayValue: 'BK Main 50',
                            value: '50',
                        },
                        {
                            uniqueKey: '4',
                            displayValue: 'Buy In',
                            value: 'B',
                        },
                        {
                            uniqueKey: '5',
                            displayValue: 'REITs',
                            value: 'T',
                        },
                    ],
                },
            ],
        },

        {
            compId: 'MktWatchMarketStatus',
            parentId: '',
            displayNameTag: 'Market Watch Market Status',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'OffMarketTrades',
            parentId: '',
            displayNameTag: 'Off Mark Trades',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'register',
            parentId: '',
            displayNameTag: 'User Registration',
            displayImage: 'slidesIcon',
            compFields: [],
        },
        {
            compId: 'login',
            parentId: '',
            displayNameTag: 'User Login',
            displayImage: 'slidesIcon',
            compFields: [],
        },
        {
            compId: 'OTCWatchList',
            parentId: '',
            displayNameTag: 'OTC WatchList',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'OTCSummary',
            parentId: '',
            displayNameTag: 'OTC Summary',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'StockScreener',
            parentId: '',
            displayNameTag: 'Stock Screener',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'fundBalanceSheet',
            parentId: '',
            displayNameTag: 'Fund Balance Sheet',
            displayImage: 'tableIcon',
            settings: [
                {
                    displayTitle: 'Enter PDF URL',
                    settingType: 'textInput',
                    dataKey: 'inputVal',
                },
            ],
            compFields: [],
        },
        {
            compId: 'ReportChart',
            parentId: '',
            displayNameTag: 'Report Chart',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'FundProfileHeader',
            parentId: '',
            displayNameTag: 'Fund Profile Header',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'productSubscriptionForm',
            parentId: '',
            displayNameTag: 'Product Subscription Form',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Customer Agreement Data',
                    settingType: 'collectionDropDownSelect',
                    dataKey: 'productSubscription',
                    settingData: [],
                },
            ],
        },

        {
            compId: 'IndexSummaryBrief',
            parentId: '',
            displayNameTag: 'Index Summary Brief',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'changeDefaultPassword',
            parentId: '',
            displayNameTag: 'User Change Default Password',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'activateUserAccount',
            parentId: '',
            displayNameTag: 'User Activatation',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'otcMarketSummary',
            parentId: '',
            displayNameTag: 'OTC Market Summary',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'otcNegotiatedDeals',
            parentId: '',
            displayNameTag: 'OTC Negotiated Deals',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'otcTopStock',
            parentId: '',
            displayNameTag: 'OTC Top Stock',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'mode',
                    settingData: [
                        {
                            uniqueKey: 'tg',
                            displayValue: 'Top Gainers by Percentages change',
                            value: 1,
                        },
                        {
                            uniqueKey: 'tl',
                            displayValue: 'Top Losers by Percentage Change',
                            value: 3,
                        },
                        {
                            uniqueKey: 'mavol',
                            displayValue: 'Most Active by Volume',
                            value: 4,
                        },
                        {
                            uniqueKey: 'mat',
                            displayValue: 'Most Active by Trades',
                            value: 5,
                        },
                        {
                            uniqueKey: 'maval',
                            displayValue: 'Most Active by Value',
                            value: 6,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'otcNews',
            parentId: '',
            displayNameTag: 'OTC News',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'otcNewsTicker',
            parentId: '',
            displayNameTag: 'OTC News Ticker',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'IncomeStatementNew',
            parentId: '',
            displayNameTag: 'Income Statement - ReactJS',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'CashFlowStatementNew',
            parentId: '',
            displayNameTag: 'Cash Flow Statement - ReactJS',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'RatiosAndIndicatorsNew',
            parentId: '',
            displayNameTag: 'Ratios and Indicators - ReactJS',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'DailyRatiosNew',
            parentId: '',
            displayNameTag: 'Daily Ratios - ReactJS',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'PriceVolumeDataNew',
            parentId: '',
            displayNameTag: 'Price Volume Data - ReactJS',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'BalanceSheetNew',
            parentId: '',
            displayNameTag: 'Balance Sheet  - ReactJS',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'economicIndicatorReact',
            parentId: '',
            displayNameTag: 'Economic Indicator React',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: 'KOP',
                            displayValue: 'Kuwait Oil Price',
                            value: 'KOP',
                        },
                        {
                            uniqueKey: 'CPI',
                            displayValue: 'CPI',
                            value: 'CPI',
                        },
                        {
                            uniqueKey: 'GDP',
                            displayValue: 'GDP',
                            value: 'GDP',
                        },
                    ],
                },
            ],
        },
        {
            compId: 'StockScreenerNew',
            parentId: '',
            displayNameTag: 'Stock Screener - Optimised',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Search Bar',
                    settingType: 'toggleSwitch',
                    dataKey: 'searchBar',
                    settingData: { defaultValue: true },
                },
                {
                    displayTitle: 'Manage Columns',
                    settingType: 'toggleSwitch',
                    dataKey: 'manageColumns',
                    settingData: { defaultValue: true },
                },
            ],
        },
        {
            compId: 'marketMakerPerformance',
            parentId: '',
            displayNameTag: 'Market Maker Performance',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'circuitBreakerTable',
            parentId: '',
            displayNameTag: 'Circuit Breaker',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'liquidityReport',
            parentId: '',
            displayNameTag: 'Liquidity Report',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'stockIDredirection',
            parentId: '',
            displayNameTag: 'Stock ID redirection',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'reitsIDredirection',
            parentId: '',
            displayNameTag: 'REITs ID redirection',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'MarketSummaryReport',
            parentId: '',
            displayNameTag: 'Market Summary Report',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'Portfolio',
            parentId: '',
            displayNameTag: 'Portfolio',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'beforeSectionSectorialData',
            parentId: '',
            displayNameTag: 'Before Section - Sectoral Data',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Regular Market',
                            value: 1,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'OTC Market',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'afterSectionSectorialData',
            parentId: '',
            displayNameTag: 'After Section - Sectoral Data',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Regular Market',
                            value: 1,
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'OTC Market',
                            value: 2,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'otcCompanyStats',
            parentId: '',
            displayNameTag: 'OTC Company Stats',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'otcMarketOverview',
            parentId: '',
            displayNameTag: 'OTC Market Overview',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'marketSummaryReportList',
            parentId: '',
            displayNameTag: 'Market Summary Report - List',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Period',
                    settingType: 'dropDown',
                    dataKey: 'period',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Monthly Reports',
                            value: 'm',
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'Annual reports',
                            value: 'y',
                        },
                    ],
                },
            ],
        },
        {
            compId: 'MarketReportTopStocks',
            parentId: '',
            displayNameTag: 'Market Report Top Stocks',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'mode',
                    settingData: [
                        {
                            uniqueKey: 'tg',
                            displayValue: 'Top Gainers by Percentages change',
                            value: 1,
                        },
                        {
                            uniqueKey: 'tl',
                            displayValue: 'Top Losers by Percentage Change',
                            value: 3,
                        },
                        {
                            uniqueKey: 'mavol',
                            displayValue: 'Most Active by Volume',
                            value: 4,
                        },
                        {
                            uniqueKey: 'maval',
                            displayValue: 'Most Active by Value',
                            value: 6,
                        },
                    ],
                },
            ],
        },
        {
            compId: 'MarketReportSummaryBySector',
            parentId: '',
            displayNameTag: 'Market Report Summary By Sector',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'MarketReportTradedCompanies',
            parentId: '',
            displayNameTag: 'Market Report Traded Companies',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'MarketReportSummary',
            parentId: '',
            displayNameTag: 'Market Report Summary',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'indexCharts',
            parentId: '',
            displayNameTag: 'Index Line Charts',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'IndexTab',
            parentId: '',
            displayNameTag: 'Market Watch Index Tab',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'multiSelect',
                    dataKey: 'collection',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Premier Market',
                            value: 'P',
                        },
                        {
                            uniqueKey: '50',
                            displayValue: 'BK Main 50',
                            value: '50',
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'Main Market',
                            value: 'M',
                        },
                        {
                            uniqueKey: '3',
                            displayValue: 'All Share',
                            value: '03',
                        },
                        {
                            uniqueKey: '4',
                            displayValue: 'Buy In',
                            value: 'B',
                        },
                        {
                            uniqueKey: '5',
                            displayValue: 'REITs',
                            value: 'T',
                        },
                        {
                            uniqueKey: '6',
                            displayValue: 'Tradable Rights',
                            value: 'TR',
                        },
                    ],
                },
            ],
        },
        {
            compId: 'RightsMarketWatch',
            parentId: '',
            displayNameTag: 'Rights Market Watch',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'marketChart',
            parentId: '',
            displayNameTag: 'Market Chart',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'type',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Premier Market',
                            value: '01',
                        },
                        {
                            uniqueKey: '50',
                            displayValue: 'BK Main 50',
                            value: '50',
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'Main Market',
                            value: '02',
                        },
                        {
                            uniqueKey: '3',
                            displayValue: 'All Share',
                            value: '03',
                        },
                    ],
                },
            ],
        },
        {
            compId: 'sectorSummaryBarChart',
            parentId: '',
            displayNameTag: 'Sector Summary - Bar Chart',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'performanceMainIndices',
            parentId: '',
            displayNameTag: 'Performance of Main Indices',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'performanceSectorIndices',
            parentId: '',
            displayNameTag: 'Performance of Sector Indices',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'marketStats',
            parentId: '',
            displayNameTag: 'Market Statistics',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'marketStatsCompareToPrevYear',
            parentId: '',
            displayNameTag: 'Market Stats Compared to Previous Year',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'marketStatsPremier',
            parentId: '',
            displayNameTag: 'Market Statistics of Premier Market',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'marketStatsMain',
            parentId: '',
            displayNameTag: 'Market Statistics of Main Market',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'marketTopStocks',
            parentId: '',
            displayNameTag: 'Top Stocks',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'marketCapBySector',
            parentId: '',
            displayNameTag: 'Market Cap Table grouped by Sector',
            displayImage: 'tableIcon',
            compFields: [],
        },

        {
            compId: 'compnyTradeInfoBySector',
            parentId: '',
            displayNameTag: 'Trade Info Table grouped by Sector',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'marketSummaryReportTitle',
            parentId: '',
            displayNameTag: 'Dynamic Title for Market Summary Report',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'TradableRightsSummary',
            parentId: '',
            displayNameTag: 'Tradable Rights Summary',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'tradableRights',
            parentId: '',
            displayNameTag: 'Tradable Rights',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'tradableRightsHistoricalData',
            parentId: '',
            displayNameTag: 'Tradable Rights - Historical Data',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'tradableRightsSummaryTab',
            parentId: '',
            displayNameTag: 'Tradable Rights - Summary Tab',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'companyInfoRights',
            parentId: '',
            displayNameTag: 'Tradable Rights - Company Info',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'RightsWatchMarketStatus',
            parentId: '',
            displayNameTag: 'Rights Issue Watch Market Status',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'marketSummarybyCompany',
            parentId: '',
            displayNameTag: 'Market Summary by Company',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'marketSummarybyCompanyList',
            parentId: '',
            displayNameTag: 'Market Summary Report by Company - List',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Period',
                    settingType: 'dropDown',
                    dataKey: 'period',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Monthly Reports',
                            value: 'm',
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'Annual reports',
                            value: 'y',
                        },
                    ],
                },
            ],
        },
        {
            compId: 'MarketWatchChart',
            parentId: '',
            displayNameTag: 'Market Watch Chart',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Chart Height',
                    settingType: 'numberInput',
                    dataKey: 'chartHeight',
                    settingData: { defaultValue: 250 },
                },
            ],
        },
        {
            compId: 'indicesBarChart',
            parentId: '',
            displayNameTag: 'Indices Bar Chart - Market Summary Report',
            displayImage: 'tableIcon',
            compFields: [],
            settings: [
                {
                    displayTitle: 'Type',
                    settingType: 'dropDown',
                    dataKey: 'type',
                    settingData: [
                        {
                            uniqueKey: '1',
                            displayValue: 'Volume',
                            value: 'volume',
                        },
                        {
                            uniqueKey: '2',
                            displayValue: 'Value',
                            value: 'value',
                        },
                        {
                            uniqueKey: '3',
                            displayValue: 'No. of Trades',
                            value: 'nooftrades',
                        },
                        {
                            uniqueKey: '4',
                            displayValue: 'Symbols Traded',
                            value: 'symbolsTraded',
                        },
                    ],
                },
            ],
        },
        {
            compId: 'instrumentProfileReact',
            parentId: '',
            displayNameTag: 'Intrument Profile - Beta',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'auditorBeta',
            parentId: '',
            displayNameTag: 'Auditors - Beta',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'boardOfDirectorsBeta',
            parentId: '',
            displayNameTag: 'Board of Directors - Beta',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'executiveManagementBeta',
            parentId: '',
            displayNameTag: 'Executive Management - Beta',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'ownershipDisclosureBeta',
            parentId: '',
            displayNameTag: 'Ownership Disclosure Of Major Share Holders - Beta',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'stockProfileInfoBeta',
            parentId: '',
            displayNameTag: 'Stock Profile - Beta',
            displayImage: 'tableIcon',
            compFields: [],
        },
        {
            compId: 'subsidiariesAndAssociatesBeta',
            parentId: '',
            displayNameTag: 'Subsidiaries And Associates - Beta',
            displayImage: 'tableIcon',
            compFields: [],
        },
    ],
};
